# Generated by Django 5.2.8 on 2025-12-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='action_items',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='key_decisions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
