# Generated by Django 5.2.9 on 2025-12-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_alter_meeting_action_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='key_decisions',
            new_name='decisions',
        ),
        migrations.AddField(
            model_name='meeting',
            name='docx',
            field=models.FileField(blank=True, null=True, upload_to='docxs/'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='speakers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='timeline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='txt',
            field=models.FileField(blank=True, null=True, upload_to='txts/'),
        ),
    ]
